[[introduction]]
= Introduction

The badass-jlink plugin allows you to create custom runtime images for modular applications with minimal effort.
It also lets you create an application installer with the https://jdk.java.net/jpackage/[jpackage] tool introduced in Java 13.

TIP:  For non-modular applications use the https://badass-runtime-plugin.beryx.org/releases/latest/[Badass-Runtime plugin].

Many modular applications have one or more non-modular dependencies, which are treated as automatic modules by the Java platform.
However, jlink cannot work with automatic modules.
The typical way to solve this problem is to convert the non-modular jars to explicit modules, by adding an appropriate module descriptor to each non-modular jar.
This is a tedious process if your application has lots of non-modular dependencies.

The badass-jlink plugin takes a more pragmatic approach by combining all non-modular dependencies into a single jar.
This way, only the resulting merged module needs a module descriptor.

The plugin provides several tasks. The most frequently used are `jlink`, which creates a custom runtime image in a given directory,
and `jlinkZip`, which in addition creates a zip archive of the custom runtime image.
With the `jpackage` task you can create a platform-specific installer for your application.

WARNING: The plugin requires Java 11 and Gradle 4.8 or newer.
While it might work with some combinations of older Java and Gradle versions, these are not officially supported.

To use the plugin, include the following in your build script:

[source,groovy]
[subs="attributes",options="nowrap"]
----
plugins {
    id 'org.beryx.jlink' version '{project-version}'
}
----

Applying the Badass-JLink plugin also implicitly applies the https://docs.gradle.org/current/userguide/application_plugin.html[Application plugin].

The plugin uses an extension named `jlink`.
The sample below shows a few configuration options.

[source,groovy]
----
jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher{
        name = 'hello'
        jvmArgs = ['-Dlog4j.configurationFile=./log4j2.xml']
    }
}
----

The next sections provide detailed information on how to configure the plugin.

NOTE: The source code is available on https://github.com/beryx/badass-jlink-plugin[GitHub] and is licensed under the {blob-root}/LICENSE[Apache-2.0 license].
